[project]
name = "irs"
version = "2.1.0"
description = "Interrogation Room Service"
dependencies = [
    "ghga-service-commons[api]>=3.0.0",
    "ghga-event-schemas>=3.0.0,<4",
    "crypt4gh>=1.6",
    "hexkit[akafka,mongodb,s3]>=2.1.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/interrogation-room-service"

[project.scripts]
irs = "irs.__main__:cli"
